# -*- coding: utf-8 -*-
"""Copy of 4-5-18-KWS-FavoriteKeywords.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1upqTKwiDgoRPY6A9Q2X2K4VsGFfq5lJw

# Generate the Model For Your Favorite Keywords (from Course 2)
This notebook builds on the [Course 2 Colab](https://colab.research.google.com/github/tinyMLx/colabs/blob/master/3-5-18-TrainingKeywordSpotting.ipynb) in which you trained your own KWS TFLite file. In this Colab you will convert that TFLite file into a TFLite Micro file which can be uploaded to your microcontroller using the Arduino IDE.

### Load the Tensorflow Lite model
You can either upload your own model from Course 2 by running the ```upload``` cell below, or you can run the ```!wget``` cell to dowload the staff's custom model from Course 2 which uses the words: "up,down,go."
"""

from google.colab import files
uploaded = files.upload()

!wget --no-check-certificate --content-disposition https://github.com/tinyMLx/colabs/blob/master/KWS_favorite.tflite?raw=true

"""### Generate a TensorFlow Lite for Microcontrollers Model
To convert the TensorFlow Lite quantized model into a C source file that can be loaded by TensorFlow Lite for Microcontrollers on Arduino we simply need to use the ```xxd``` tool to convert the ```.tflite``` file into a ```.cc``` file. **Note: if the file you uploaded is not called ```KWS_favorite.tflite``` make sure to either rename it or update the ```MODEL_TFLITE``` variable below.**
"""

!apt-get update && apt-get -qq install xxd

MODEL_TFLITE = 'KWS_favorite.tflite'
MODEL_TFLITE_MICRO = 'KWS_favorite.cc'
!xxd -i {MODEL_TFLITE} > {MODEL_TFLITE_MICRO}
REPLACE_TEXT = MODEL_TFLITE.replace('/', '_').replace('.', '_')
!sed -i 's/'{REPLACE_TEXT}'/g_model/g' {MODEL_TFLITE_MICRO}

"""That's it! You've successfully converted your TensorFlow Lite model into a TensorFlow Lite for Microcontrollers model! Run the cell below to print out its contents which we'll need for our next step, deploying the model using the Arudino IDE! **So don't close this Colab as we'll use the model printout in the next step of the deployment to the Arduino IDE!**"""

!cat {MODEL_TFLITE_MICRO}

"""If you'd like to download your model for safekeeping:
1. On the left of the UI click on the folder icon
2. Click on the three dots to the right of the ```KWS_favorite.cc``` file and select download
"""